name: CI
on: [push]
env:
  CI: 'true'
jobs:
  tests:
    strategy:
      matrix:
        java: [11,14]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    name: java-${{ matrix.java }} tests
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/mvnw') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - run: cd $GITHUB_WORKSPACE && ./mvnw
  step-0-no-security:
    strategy:
      matrix:
        java: [11,14]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    name: java-${{ matrix.java }} step-0-no-security
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
    - uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-maven-${{ hashFiles('**/mvnw') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - uses: actions/cache@v1
      with:
        path: ~/.node
        key: ${{ runner.os }}-maven-${{ hashFiles('**/mvnw') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/mvnw') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - run: npm i -g wait-port
    - run: sudo apt-get install -yqq httpie
    - run: cd $GITHUB_WORKSPACE && ./mvnw -f step-0-no-security
    - run: bash $GITHUB_WORKSPACE/step-0-no-security/target/*jar &
    - run: wait-port 8080
    - run: http get :8080
    - run: http get :8080/api/hello
